Sprint1-tentativePlan.md, frontend/.gitignore, frontend/src/Components/Home.jsx, frontend/src/Components/Signup.jsx
- Added fields for SignUp 
- Updated Home with Links
=> Added fields for SignUp and updated Home with Links

.gitignore
=> Added a global gitignore file

frontend/public/index.html, frontend/src/App.css, frontend/src/App.js, frontend/src/Components/Login.jsx, frontend/src/Components/Signup.jsx, frontend/src/index.css
added complete homepage, buttons and CSS
=> [Froneend] added complete homepage, buttons and CSS

frontend/package-lock.json, frontend/package.json, frontend/src/Components/Signup.jsx, frontend/src/index.js, frontend/src/server.js
- Added API Mocking for SignUp page
- Added Mirage and Axios packages
=> [Frontend] Added MirageJS for mocking apis

frontend/src/Components/Login.jsx, frontend/src/server.js
Added login API mock in Login page
=> [Frontend] Added login API mock

backend/dbConnection.go, backend/dbOperations.go, backend/dummy.go, backend/main.go, backend/requestHandlerConfig.go, backend/requestHandlerFunc.go, backend/structTypes.go
Refactored the code into multiple files.
**TODO**: Refactoring to packages
=> Refactoring code to multiple files

frontend/src/Components/Header.jsx
Added highlighting current page in header
=> [Frontend] Added highlighting current page in header

frontend/src/Components/TimeSelect.jsx, frontend/src/server.js
Added validation for booking pane
=> [Frontend] Added validation for booking pane

frontend/src/App.js, frontend/src/Components/Bookings.jsx, frontend/src/Components/Header.jsx, frontend/src/server.js
Added basic layout for bookings page with API call and mocked up server
=> [Frontend] Added basic layout for bookings page with API call and mocked up server

frontend/cypress.json, frontend/cypress/support/commands.js, frontend/package-lock.json, frontend/package.json
Added additional config for Cypress
=> [Frontend] Added additional config for Cypress

frontend/cypress/integration/SignUp/SignUp.spec.js, frontend/cypress/integration/VendorLogin/VendorLogin.spec.js, frontend/cypress/mirage/devServer.js, frontend/src/Components/Signup.jsx, frontend/src/Components/VendorLogin.jsx
Added tests for login and vendor's login
=> [Frontend] Added tests for Login and VendorLogin

frontend/cypress.json, frontend/cypress/integration/Dashboard/Dashboard.spec.js, frontend/cypress/integration/LoginTest/Login.spec.js, frontend/cypress/integration/SignUp/SignUp.spec.js, frontend/cypress/support/commands.js, frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/Components/Dashboard.jsx, frontend/src/Components/Header.jsx, frontend/src/Components/TimeSelect.jsx
Added Dashboard test cases using automated login command
=> [Frontend] Added Dashboard test cases using automated login command

frontend/cypress/integration/Profile/Profile.spec.js, frontend/src/Components/Profile.jsx
Added cypress tests for Profile
=> [Frontend] Added cypress tests for Profile

frontend/src/Components/VendorLogin.jsx, frontend/src/Components/VendorSignup.jsx
=> [Frontend] Updated vendor login

frontend/src/App.js, frontend/src/Components/Vendorprofile.jsx
=> Add vendor profile

frontend/src/Components/Vendorprofile.jsx, frontend/src/index.css
=> Improve vendor profile ux

frontend/src/Components/Profile.jsx, frontend/src/Components/Vendorprofile.jsx, frontend/src/index.css
=> Improve user profile UX

frontend/package-lock.json, frontend/src/Components/Bookings/Bookings.jsx, frontend/src/Components/VendorBooking.jsx, frontend/src/Components/VendorDashboard.jsx, frontend/src/server.js
Add ratings functionality to the vendor side.
=> Add ratings functionality to vendor side

frontend/src/Components/Bookings/Bookings.jsx, frontend/src/Components/VendorDashboard.jsx, frontend/src/server.js
Add status of booking for vendor and customer.
=> Add status of booking for vendor and customer

frontend/cypress/integration/LoginTest/Login.spec.js, frontend/src/Components/Bookings/Booking.jsx, frontend/src/Components/Bookings/Bookings.jsx, frontend/src/Components/VendorBooking.jsx, frontend/src/Components/VendorDashboard.jsx, frontend/src/index.css
UX changes to vendor and customer booking
=> UX changes to vendor and customer booking

frontend/src/Components/Bookings/Booking.jsx, frontend/src/Components/Bookings/Bookings.jsx
Bug fixes on the user booking side.
=> Bug fixes on the user booking side

backend/dbOperations/dbOperations.go
Joining booking and city table on booking's city id
=> Bug fix in get bookings

frontend/src/Components/Bookings/Bookings.jsx
Changed status indicator colours.
=> Changed status indicator colours.

frontend/src/Components/TimeSelect.jsx, frontend/src/index.css
Changes to the timeselect modal
=> Changes to the timeselect modal

frontend/src/Components/Bookings/Booking.jsx, frontend/src/Components/VendorBooking.jsx
Customer and vendor can call each other.
=> Customer and vendor can call each other 

frontend/src/Components/Bookings/Booking.jsx
Bug fix in reschedule date cards.
=> Bug fix in reschedule date cards

backend/dbOperations/dbOperations.go, backend/requestHandlers/requestHandlerFunc.go, backend/router/router.go, backend/structTypes/requestStructs.go, backend/structTypes/responseStructs.go
Updated OTP verification for service start and service end initiated by Vendor
=> OTP verification

backend/dbOperations/dbOperations.go
Updated queries for booking status updates
=> updated queries

frontend/cypress/integration/UserJourney/UserJourney.spec.js, frontend/src/Components/Header.jsx, frontend/src/index.css
Added Cypress for user journey 1
=> Added Cypress for user journey 1

frontend/cypress/integration/UserJourney/UserJourney.spec.js, frontend/cypress/integration/UserRating/UserRating.spec.js
Added cypress tests for user rating a vendor
=> Added cypress tests for user rating a vendor

backend/dbOperations/dbOperations.go
=> final fixes for booking completion
